pendo-io/pendo-mobile-sdk

README.md, pnddocs/native.md, pnddocs/swiftui_beta.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/12)
=> Changing documentation for SwiftUI beta

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/13)
=> Forward slash in url 

pnddocs/swiftui_beta.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/15)
=> Swift UI docs update

README.md, pnddocs/swiftui.md, pnddocs/swiftui_beta.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/16)
=> SwiftUI official

README.md, pnddocs/maui.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/22)
=> APP-71711 maui instructions

pnddocs/swiftui.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/30)
=> APP-76862 Swiftui update docs

pnddocs/expo_native_navigation.md, pnddocs/react_native_navigation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/33)
=> APP-80331 fix RNN initPendo step

pnddocs/swiftui.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-ios/36)
=> APP-80950 fix url sample app 

android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, ios/README.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/42)
=> App 81788 update

android/pnddocs/flutter-android.md, android/pnddocs/native-android.md, ios/pnddocs/expo_rn.md, ios/pnddocs/expo_rnn.md, ios/pnddocs/flutter-ios.md, ios/pnddocs/native-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md, ios/pnddocs/swiftui.md, ios/pnddocs/xamarin-ios.md, ios/pnddocs/xamarin_forms-ios.md, ios/pnddocs/xamarin_maui-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/43)
=> APP-82169 added missing instructions

.github/ISSUE_TEMPLATE/bug_report.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/49)
=> APP-83562_Bug_format

android/pnddocs/expo_rn.md, android/pnddocs/expo_rnn.md, android/pnddocs/flutter-android.md, android/pnddocs/native-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, android/pnddocs/xamarin-android.md, android/pnddocs/xamarin_forms-android.md, android/pnddocs/xamarin_maui-android.md, ios/pnddocs/expo_rn.md, ios/pnddocs/expo_rnn.md, ios/pnddocs/flutter-ios.md, ios/pnddocs/native-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md, ios/pnddocs/swiftui.md, ios/pnddocs/xamarin-ios.md, ios/pnddocs/xamarin_forms-ios.md, ios/pnddocs/xamarin_maui-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/59)
=> APP-85331 update scheme and app key to api and note where to find them

android/pnddocs/native-android.md, android/pnddocs/xamarin-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/61)
=> APP-85914 pendoOptions

android/pnddocs/pendo-proguard.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/69)
=> APP-86708 proguard rules updated, parametrizedType

ios/pnddocs/flutter-ios.md, ios/pnddocs/native-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md, ios/pnddocs/swiftui.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/71)
=> APP-88062 adding some scene delegate documentation

README.md, migration-docs/README.md, migration-docs/android-2.x-to-3.x-migration.md, migration-docs/flutter-2.x-to-3.x-migration.md, migration-docs/ios-2.x-to-3.x-migration.md, migration-docs/maui-2.x-to-3.x-migration.md, migration-docs/react-native-2.x-to-3.x-migration.md, migration-docs/xamarin-forms-2.x-to-3.x-migration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/77)
=> APP-88575 migration docs

android/pnddocs/xamarin_forms-android.md, android/pnddocs/xamarin_maui-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/78)
=> APP-89204 v13 for android

android/pnddocs/expo_rn-android.md, android/pnddocs/expo_rnn-android.md, ios/pnddocs/expo_rn-ios.md, ios/pnddocs/expo_rnn-ios.md, ios/pnddocs/native-ios.md, ios/pnddocs/xamarin_forms-ios.md, ios/pnddocs/xamarin_maui-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/94)
=> APP-93557 documentation improvements

api-documentation/rn-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/96)
=> APP-93905 copy fix

ios/pnddocs/native-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/98)
=> APP-93962 fix ios install

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/99)
=> APP-94328 Update version to 3.0.1

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/101)
=> Remove Empty line from Package.swift

README.md, android/pnddocs/flutter-android.md, android/pnddocs/native-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, android/pnddocs/xamarin_forms-android.md, android/pnddocs/xamarin_maui-android.md, ios/pnddocs/native-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/100)
=> APP-93138 update sdk profiling section

Package.swift
release iOS 3.0.2.8105
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/103)
=> APP-95364 Update Package.swift

api-documentation/flutter-apis.md, api-documentation/native-android-apis.md, api-documentation/native-ios-apis.md, api-documentation/rn-apis.md, api-documentation/xamarin-forms-apis.md, api-documentation/xamarin-maui-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/106)
=> APP-94641 Updated all frameworks pauseGuides API documentation

android/pnddocs/xamarin_maui-android.md, ios/pnddocs/xamarin_maui-ios.md, migration-docs/maui-2.x-to-3.x-migration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/108)
=> APP-94830 pendo effects in maui (3.1)

api-documentation/native-ios-apis.md, migration-docs/ios-2.x-to-3.x-migration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/111)
=> APP-96825 update swiftUI docs

android/pnddocs/android_sdk_manual_installation.md, android/pnddocs/native-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/112)
=> APP-95046 3.1 updates

android/pnddocs/native-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/120)
=> APP-98544 additional note explaining jetpack is track event only

android/pnddocs/xamarin_maui-android.md, ios/pnddocs/xamarin_maui-ios.md, migration-docs/maui-2.x-to-3.x-migration.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/127)
=> APP-99209 add .NET 8 support to docs

android/pnddocs/expo_rn-android.md, android/pnddocs/expo_rnn-android.md, android/pnddocs/flutter-android.md, android/pnddocs/native-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, android/pnddocs/xamarin_forms-android.md, android/pnddocs/xamarin_maui-android.md, ios/pnddocs/expo_rn-ios.md, ios/pnddocs/expo_rnn-ios.md, ios/pnddocs/flutter-ios.md, ios/pnddocs/native-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md, ios/pnddocs/xamarin_forms-ios.md, ios/pnddocs/xamarin_maui-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/128)
=> APP-99328 fix urls

ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/129)
=> APP-99369 add override keywork

Package.swift
version update
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/130)
=> APP-99673 Update Package.swift

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/131)
=> APP-99851 Update Package.swift

README.md, android/pnddocs/android_sdk_manual_installation.md, android/pnddocs/expo_rn-android.md, android/pnddocs/expo_rnn-android.md, android/pnddocs/flutter-android.md, android/pnddocs/native-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, android/pnddocs/xamarin_forms-android.md, android/pnddocs/xamarin_maui-android.md, api-documentation/native-android-apis.md, api-documentation/native-ios-apis.md, ios/pnddocs/expo_rn-ios.md, ios/pnddocs/expo_rnn-ios.md, ios/pnddocs/flutter-ios.md, ios/pnddocs/native-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md, ios/pnddocs/xamarin_forms-ios.md, ios/pnddocs/xamarin_maui-ios.md, other/native-with-flutter-components.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/133)
=> App 83565 native with flutter components

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/141)
=> APP-101987 fix swift package

android/pnddocs/expo_rn-android.md, android/pnddocs/expo_rnn-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, ios/pnddocs/expo_rn-ios.md, ios/pnddocs/expo_rnn-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md
https://github.com/pendo-io/pendo-mobile-sdk/issues/115#issuecomment-2122280426
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/144)
=> APP-102415 min requirements for RN.

README.md, android/pnddocs/expo_rn-android.md, android/pnddocs/expo_rnn-android.md, android/pnddocs/expo_router-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, api-documentation/rn-apis.md, ios/pnddocs/expo_rn-ios.md, ios/pnddocs/expo_rnn-ios.md, ios/pnddocs/expo_router-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/146)
=> APP-102949 add expo router documentation

README.md, android/pnddocs/android_sdk_manual_installation.md, android/pnddocs/jetpack_compose-android.md, android/pnddocs/native-android.md, other/native-with-flutter-components.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/149)
=> APP-99856 jpc install instructions

android/pnddocs/jetpack_compose-android.md, android/pnddocs/native-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/150)
=> APP-99856 jpc url fixes.

android/pnddocs/native-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/156)
=> APP-105845 require setup to be called on app launch

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md, other/flutter-code-samples.md, other/flutter-notes-known-issues-limitations.md, other/native-with-flutter-components.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/157)
=> APP-104740_flutter_codeless_docs

android/pnddocs/jetpack_compose-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/159)
=> APP-106304 update lifecycleResumeEffect

android/pnddocs/expo_rn-android.md, android/pnddocs/expo_rnn-android.md, android/pnddocs/expo_router-android.md, android/pnddocs/flutter-android.md, android/pnddocs/native-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, ios/pnddocs/expo_rn-ios.md, ios/pnddocs/expo_rnn-ios.md, ios/pnddocs/expo_router-ios.md, other/native-with-flutter-components.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/160)
=> APP-106394 allProjects fix

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md, other/flutter-code-samples.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/163)
=> APP-107124 update Go router docs

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/167)
=> APP-107575_update_requirements

api-documentation/native-android-apis.md, api-documentation/rn-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/170)
=> APP-108450 sendClickAnalytic name fix

api-documentation/native-android-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/175)
=> APP-108874 update android onInitComplete callback descreption

api-documentation/native-ios-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/178)
=> APP-109311_ios_notification_style2

ios/pnddocs/native-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/173)
=> APP-108693 swiftui section

README.md, benchmarks/FlutterPerformanceBenchmarks.md, benchmarks/NativePerformanceBenchmarks.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/180)
=> APP-108711 formatting benchmark files

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/182)
=> APP-109723

android/pnddocs/android_sdk_manual_installation.md, android/pnddocs/native-android.md, other/native-with-flutter-components.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/186)
=> APP-110254 3.4 update

Package.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/187)
=> APP-110402

Package.swift
This reverts commit a874fdc98bed78f229d7bf357827cea229dee764.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/195)
=> APP-111611 Reverting back to 3.4.2 from 3.4.3

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/199)
=> APP-111637 update about obfuscation + remove beta

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/204)
=> APP-111911 add NavigationLibrary to setup call

api-documentation/rn-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/205)
=> APP-112745 fix modal type to be more accurate

api-documentation/native-ios-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/207)
=> APP-113581 setup and startSession clarifications

api-documentation/native-android-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/214)
=> APP-113681 Adjust a setup and startSession api documentation

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/215)
=> APP-113569 highly recommend naming

ios/pnddocs/native-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/223)
=> APP-116469 Added new flag to documentation using in swiftUI

android/pnddocs/native-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/228)
=> APP-115850 minor indentation change

api-documentation/rn-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/217)
=> APP-114202 Add support for gorhom/BottomSheetModal

android/pnddocs/xamarin_maui-android.md, ios/pnddocs/xamarin_maui-ios.md, ±
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/230)
=> APP-119139 maui_updates

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/234)
=> APP-119740 flutter 3.6.2 documentation

android/pnddocs/flutter-android.md, ios/pnddocs/flutter-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/236)
=> APP-119902 typo fix

android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/237)
=> APP-118693 update rn version to 078

android/pnddocs/native-android.md, api-documentation/native-android-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/239)
=> APP-118549 pendotag expansion

android/pnddocs/native-android.md
https://pendo-io.atlassian.net/browse/APP-121005
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/240)
=> APP-121005 verify pendoTag is uniquely added

android/pnddocs/native-android.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/242)
=> APP-121007 JPC androidx.compose.ui 1.5.0 or higher requirement

android/pnddocs/native-android.md, api-documentation/native-android-apis.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/245)
=> APP-119739 updated android instructions for jetpack ga

android/pnddocs/android_sdk_manual_installation.md, android/pnddocs/native-android.md, other/native-with-flutter-components.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/248)
=> APP-118841 3.7 release

api-documentation/native-ios-apis.md, ios/pnddocs/native-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/241)
=> APP-116434

.gitignore, android/pnddocs/expo_rn-android.md, android/pnddocs/expo_rnn-android.md, android/pnddocs/expo_router-android.md, android/pnddocs/native-android.md, android/pnddocs/rn-android.md, android/pnddocs/rnn-android.md, android/pnddocs/xamarin_forms-android.md, android/pnddocs/xamarin_maui-android.md, api-documentation/native-android-apis.md, api-documentation/native-ios-apis.md, api-documentation/rn-apis.md, api-documentation/xamarin-forms-apis.md, api-documentation/xamarin-maui-apis.md, benchmarks/NativePerformanceBenchmarks.md, ios/pnddocs/expo_rn-ios.md, ios/pnddocs/expo_rnn-ios.md, ios/pnddocs/expo_router-ios.md, ios/pnddocs/native-ios.md, ios/pnddocs/rn-ios.md, ios/pnddocs/rnn-ios.md, ios/pnddocs/xamarin_forms-ios.md, ios/pnddocs/xamarin_maui-ios.md, migration-docs/README.md, other/flutter-notes-known-issues-limitations.md
- **APP-118287 containers view doc**
- **APP-118287 ignore .build**
- **APP-118287 more docs**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/253)
=> APP-118287

android/pnddocs/native-android.md, ios/pnddocs/native-ios.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pendo-io/pendo-mobile-sdk/256)
=> APP-124434
